import './style.css';
import 'katex/dist/katex.min.css';
import {marked} from 'marked';
import DOMPurify from 'dompurify';
import katex from 'katex';
import {protectMath} from './markdown-math.js';
import catalog from '../content/catalog.json';
import sources from '../content/sources.json';
import archive from '../content/archive-catalog.json';
import curriculum from '../content/curriculum.json';
import {selectLessons,neighbors,noteIds} from './curriculum.js';
import {interviewPrompts} from './interview.js';
import {renderDiagrams} from './diagrams.js';
import {THEME_KEY,resolveTheme,oppositeTheme} from './theme.js';
import {mountPrivateLibrary} from './private-library.js';
let privateViewCleanup;
const allLessons=[...catalog,...archive];
const hasInternal=catalog.some(l=>l.internal), hasArchive=archive.length>0, hasWorkbuddy=catalog.some(l=>l.stage==='workbuddy');
import {emptyState,validateState,mergeState,kvBytes,advantages} from './logic.js';
const articles=import.meta.glob('../content/lessons/*.md',{query:'?raw',import:'default',eager:true});
const ids=noteIds(catalog,archive), key='agent-learning-atlas.v1';
let state=emptyState(), storageOk=true, search='', filter='all';
const colorScheme=window.matchMedia('(prefers-color-scheme: dark)');
let savedTheme;
try { savedTheme=localStorage.getItem(THEME_KEY); } catch {}
let theme=resolveTheme(savedTheme,colorScheme.matches);
function applyTheme(next){
 theme=next;
 document.documentElement.dataset.theme=next;
 document.documentElement.style.colorScheme=next;
 document.querySelector('meta[name="theme-color"]')?.setAttribute('content',next==='dark'?'#191a18':'#f3f1e9');
 const button=document.querySelector('#theme-toggle');
 if(button){button.textContent=next==='dark'?'☀ 日间':'☾ 夜间';button.setAttribute('aria-label',next==='dark'?'切换到日间模式':'切换到夜间模式');button.setAttribute('aria-pressed',String(next==='dark'));}
}
applyTheme(theme);
colorScheme.addEventListener('change',event=>{if(!savedTheme)applyTheme(resolveTheme(null,event.matches));});
try { const old=localStorage.getItem(key); if(old) state=validateState(JSON.parse(old),ids); } catch { storageOk=false; }
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const tracks=Object.fromEntries(curriculum.stages.map(s=>[s.id,s.title]));
const types={source:'源码',paper:'论文',official:'官方文档',community:'博客与论坛',writing:'写作与教学'};
function entry(id){return state.lessons[id]||{status:'unread',note:'',updated:0};}
function save(){try {localStorage.setItem(key,JSON.stringify(state));storageOk=true;}catch{storageOk=false;} }
function update(id,change){state.lessons[id]={...entry(id),...change,updated:Date.now()};save();}
const statusText={unread:'未读',review:'待巩固',understood:'能复述'};
function toast(message){const el=document.querySelector('#toast');el.textContent=message;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),3500);}
const kindLabel={optional:'选读', 'case-study':'案例',implementation:'实现专题'};
function card(l){return '<a class="lesson-card" href="#/lesson/'+l.id+'"><span class="card-top"><span class="mono">'+String(l.order).padStart(2,'0')+'</span><span>'+(kindLabel[l.kind]?'<em class="lesson-kind">'+kindLabel[l.kind]+'</em> · ':'')+l.minutes+' 分钟 · '+statusText[entry(l.id).status]+'</span></span><h3>'+esc(l.title)+'</h3><p>'+esc(l.summary)+'</p><span class="card-bottom">'+esc(l.goal||l.anchor||'独立知识点')+'<b>↗</b></span></a>';}
function shell(active){
 document.querySelector('#app').innerHTML='<a class="skip" href="#main">跳到正文</a><aside class="sidebar"><a href="#/" class="brand"><span class="brand-mark">知</span><span>知行图谱<small>AGENT LEARNING ATLAS</small></span></a><div class="personal">NATHAN’S LEARNING SPACE</div><nav aria-label="主导航">'+[['home','学习首页','◈','#/'],['path','知识路线','⌁','#/path'],['internal','M365 平台五篇','▦','#/path/internal'],['private','加密资料','▣','#/private'],['interview','面试自测','◎','#/interview'],['lab','交互实验室','◇','#/lab'],['sources','阅读与来源','▤','#/sources'],['notes','我的笔记','▧','#/notes']].filter(([id])=>id!=='internal'||hasInternal).map(([id,label,icon,url])=>'<a '+(active===id?'class="active" aria-current="page"':'')+' href="'+url+'"><i>'+icon+'</i>'+label+'</a>').join('')+'</nav><div class="sidebar-divider"></div><p class="nav-label">按阶段学习</p>'+curriculum.stages.map(s=>'<a class="track-link" href="#/path/'+s.id+'">'+s.number+' · '+s.title+'</a>').join('')+(hasArchive?'<a class="track-link" href="#/archive">旧版文章与笔记</a>':'')+'<div class="sidebar-bottom"><div class="small-badge">LOCAL-FIRST</div><p>从一个问题出发，<br>把机制讲清楚。</p><small>课程更新 · 2026.10.03</small></div></aside><div class="workspace"><header class="topbar"><button id="menu" class="icon-btn" aria-label="切换导航">☰</button><span class="breadcrumb">学习是一条连续的路径</span><div class="top-actions"><button id="theme-toggle" class="theme-toggle" type="button" aria-label="切换颜色模式"></button><a class="search-link" href="#/path">搜索课程 <kbd>/</kbd></a></div></header><main id="main" tabindex="-1"></main><footer>知行图谱 <span>·</span> 基于公开证据与实际项目 <span>·</span> 阅读状态由你定义</footer></div><div id="toast" role="status" aria-live="polite"></div>';
 document.querySelector('#menu').onclick=()=>document.body.classList.toggle('nav-open');
 document.querySelector('.skip').onclick=event=>{event.preventDefault();document.querySelector('#main').focus();};
 applyTheme(theme);
 document.querySelector('#theme-toggle').onclick=()=>{const next=oppositeTheme(theme);savedTheme=next;try{localStorage.setItem(THEME_KEY,next);}catch{}applyTheme(next);};
}
function stageBlock(stage,list){
 const extensions=stage.id==='research'&&hasArchive?'<div class="research-branches"><h3>继续分支阅读</h3><p>以下保留旧版资料，作为后续选题入口；尚未按独立知识点重写，内容中的版本与证据日期需分别核对。</p><div><a href="#/lesson/model-map">国内路线 · DeepSeek / Qwen / GLM / Hunyuan ↗</a><a href="#/lesson/frontier">国际路线 · OpenAI / Claude 的公开方法与未知 ↗</a><a href="#/lesson/multimodal">多模态表示 ↗</a><a href="#/lesson/efficiency">KV cache 与推理效率 ↗</a></div></div>':'';
 return '<section class="section stage-section"><div class="section-heading"><div><span class="eyebrow">STAGE '+stage.number+'</span><h2>'+esc(stage.title)+'</h2><p class="muted">'+esc(stage.description)+'</p></div><a class="text-link" href="#/path/'+stage.id+'">单独看这一阶段 →</a></div><div class="card-grid">'+list.map(card).join('')+'</div>'+extensions+'</section>';
}
function workbuddyEntry(){return hasWorkbuddy?'<section class="reading-banner workbuddy-entry"><div><span class="eyebrow">WORKBUDDY · 5.6.2</span><h2>沿着一次请求，读懂桌面 Agent 的实现</h2><p>先读 Electron 与 Edge/Chromium 的进程管理，再用八篇实现文章解释会话连接、Prompt 装配、Skill 加载、MCP 调用、文档交接、研究编排、历史压缩与故障恢复。每篇保留代码定位、完整例子和失败分支。</p></div><a class="button primary" href="#/path/workbuddy">阅读 WorkBuddy 系列 →</a></section>':'';}
function home(){
 const done=catalog.filter(l=>entry(l.id).status==='understood').length;
 const next=catalog.find(l=>l.id===state.lastLesson)||catalog[0];
 document.querySelector('#main').innerHTML='<section class="hero staged-hero"><div class="hero-copy"><span class="eyebrow">AGENT · 从基础工程到研究</span><h1>先把一个知识点<span>讲明白。</span></h1><p>先看一次模型请求如何变成行动，再依次补齐工具、状态、检索、协作和评估。模型结构与训练研究放在后面，按需要分支深入。</p><a class="button primary" href="#/lesson/'+next.id+'">'+(state.lastLesson===next.id?'继续阅读':'从 LLM 请求开始')+' ↗</a><a class="text-link" href="#/interview">面试自测 →</a></div></section><div class="learning-sequence">'+curriculum.stages.map(st=>'<a href="#/path/'+st.id+'"><small>'+st.number+'</small><b>'+esc(st.title)+'</b></a>').join('')+'</div><section class="stats-strip"><div><strong>'+catalog.length+'</strong><span>个学习页面</span></div><div><strong>'+curriculum.stages.length+'</strong><span>个学习阶段与专题</span></div><div><strong>27</strong><span>个原始面试主题已映射</span></div><div><strong>'+done+'</strong><span>篇标记为能复述</span></div></section><section class="reading-banner"><div><h2>面试先读到哪里？</h2><p>01—05 是 Agent 工程主线；05.5 补 Agent 平台的运行、隔离、协议和交付；06 补 Transformer、SFT、RLHF。每篇末尾有短答、追问与练习。07 是研究分支。'+(hasInternal?'M 是 M365 平台五篇，先看全景，再沿知识、运行循环、工具和长任务阅读。':'')+'</p></div><a class="button light" href="#/path">完整目录 ↗</a></section>'+(hasInternal?'<section class="reading-banner internal-entry"><div><span class="eyebrow">INTERNAL ARCHITECTURE</span><h2>M365 Copilot 平台，用五篇串起来</h2><p>沿内容、工具、包与运行时理解工作系统。可直接从架构总览进入，再按需要回看基础课。</p></div><a class="button primary" href="#/path/internal">打开内部路线 ↗</a></section>':'')+workbuddyEntry()+stageBlock(curriculum.stages[0],catalog.filter(l=>l.stage==='foundation'));
}
function path(track='all'){
 const main=document.querySelector('#main');
 main.innerHTML='<div class="page-head"><span class="eyebrow">LEARNING PATH</span><h1>'+ (track==='workbuddy'?'WorkBuddy 工程剖析：进程基础与八篇实现':track==='internal'?'把基础知识接到 M365 架构':'从基础工程，走到研究与平台实现')+'</h1><p>01—05 建立 Agent 工程基础，05.5 补企业 Agent 平台，06 理解模型训练基础，07 深入研究。'+(hasInternal?'M365 内部路线重整为五篇：全景、知识、运行循环、工具与长任务。':'')+'WorkBuddy 系列先补桌面与浏览器进程基础，再沿会话入口逐篇阅读。搜索也会匹配面试主题。</p></div><div class="filters"><label class="search-box"><span>⌕</span><input id="course-search" type="search" placeholder="搜索知识点，例如 MCP、分块、RLHF…" aria-label="搜索课程" value="'+esc(search)+'"></label><div class="pills" role="group" aria-label="课程分类">'+[['all','全部'],['internal','M365 内部架构'],...Object.entries(tracks)].filter(([id])=>id!=='internal'||hasInternal).map(([id,label])=>'<button data-track="'+id+'" class="pill '+(track===id?'selected':'')+'">'+label+'</button>').join('')+'</div></div><div id="course-results"></div>';
 const show=()=>{const list=selectLessons(catalog,track,search);document.querySelector('#course-results').innerHTML=list.length?curriculum.stages.map(st=>{const ls=list.filter(l=>l.stage===st.id);return ls.length?stageBlock(st,ls):'';}).join(''):'<div class="empty">没有匹配课程，试试具体术语或中文名。</div>';};show();
 document.querySelector('#course-search').oninput=e=>{search=e.target.value;show();};document.querySelectorAll('[data-track]').forEach(e=>e.onclick=()=>{location.hash='#/path/'+e.dataset.track;});
}
function archived(){document.querySelector('#main').innerHTML='<div class="page-head"><span class="eyebrow">ARCHIVE</span><h1>旧版文章与原有笔记</h1><p>原文章保留供查阅。混合主题已拆到新路线；旧阅读状态与笔记仍属于原文，不自动迁移为新课掌握记录。</p><a class="text-link" href="#/path">打开分层课程 →</a></div><div class="card-grid">'+archive.map(card).join('')+'</div>';}
function interview(){document.querySelector('#main').innerHTML='<div class="page-head"><span class="eyebrow">INTERVIEW PRACTICE</span><h1>能回答定义，再试着接住追问</h1><p>先不看文章，用自己的话回答。每篇末尾可展开口头回答和追问参考，再用练习检查是否真正理解。这里覆盖原始面试主题与工程基础。'+(hasInternal?'内部架构篇仅供授权范围内学习，面试讲述仍需遵守信息披露边界。':'')+'</p></div>'+curriculum.stages.filter(s=>s.id!=='research').map(st=>'<section class="section"><h2>'+esc(st.title)+'</h2><div class="interview-list">'+catalog.filter(l=>l.stage===st.id).map(l=>'<a href="#/lesson/'+l.id+'"><b>'+esc(l.title)+'</b><span>'+esc(l.summary)+'<ul>'+interviewPrompts(articles['../content/lessons/'+l.id+'.md']||'').map(q=>'<li>'+esc(q)+'</li>').join('')+'</ul></span><small>阅读解释与追问 →</small></a>').join('')+'</div></section>').join('');}
function lesson(id){
 const l=allLessons.find(x=>x.id===id); if(!l){document.querySelector('#main').innerHTML='<div class="empty"><h1>没有找到这篇课程</h1><a href="#/path">回到知识路线</a></div>';return;}
 state.lastLesson=id;save();const e=entry(id);const isArchive=archive.some(x=>x.id===id);const {previous:prev,next}=neighbors(isArchive?archive.map(x=>({...x,stage:'archive'})):catalog,id);const nextStage=isArchive?undefined:curriculum.stages[curriculum.stages.findIndex(s=>s.id===l.stage)+1];
 const original=articles['../content/lessons/'+id+'.md'];
 const {protectedText:raw,equations}=protectMath(original);
 document.querySelector('#main').innerHTML='<div class="article-top"><a href="#/path">← 知识路线</a><span>'+(tracks[l.stage]||'旧版归档')+' / '+l.minutes+' 分钟</span></div><div class="article-layout"><div>'+(l.internal?'<div class="internal-notice">内部学习材料 · 固定源码与文档证据；不代表当前生产配置。引用需要公司权限。</div>':'')+'<div class="article-anchor"><span>'+ (isArchive?'旧版归档 · 新版请从知识路线进入':'本篇要回答的问题')+'</span><b>'+esc(l.goal||l.title)+'</b></div><article class="prose">'+DOMPurify.sanitize(marked.parse(raw),{ADD_ATTR:['target']})+'</article><section class="reflection"><span class="eyebrow">MAKE IT YOURS</span><h2>把它变成自己的理解</h2><p>合上文章，你会怎样解释这个概念？哪个例子还有疑问？</p><label>这篇课目前对你来说<select id="status"><option value="unread">未读</option><option value="review">读过，待巩固</option><option value="understood">能用自己的例子复述</option></select></label><label for="note">自己的理解 / 哪里没懂</label><textarea id="note" maxlength="30000" placeholder="例如：我懂了 KV-cache 的存储，但还不明白 MLA 的低秩压缩与 LoRA 有何不同…">'+esc(e.note)+'</textarea><div class="note-bottom"><span id="save-status">'+(storageOk?'仅保存在此浏览器，可在“我的笔记”导出。':'浏览器存储不可用；当前修改请及时导出。')+'</span><a href="#/notes">导出笔记 ↗</a></div></section><div class="article-pager">'+(prev?'<a href="#/lesson/'+prev.id+'"><small>上一篇</small>'+esc(prev.title)+' ←</a>':'<span></span>')+(next?'<a href="#/lesson/'+next.id+'"><small>下一篇</small>'+esc(next.title)+' →</a>':nextStage?'<a href="#/path/'+nextStage.id+'"><small>完成本阶段后</small>'+esc(nextStage.title)+' →</a>':'<a href="#/path">回到知识路线 →</a>')+'</div></div><aside class="article-rail"><span class="nav-label">阅读之前</span>'+(l.prerequisites.length?l.prerequisites.map(x=>'<a href="#/lesson/'+x+'">'+esc(allLessons.find(a=>a.id===x)?.title||x)+' ↗</a>').join(''):'<p>具备基本编程常识即可开始。</p>')+'<span class="nav-label">这篇文章</span><div id="toc"></div><span class="nav-label">证据与阅读</span>'+l.sourceIds.map(x=>{const s=sources.find(a=>a.id===x);return '<a target="_blank" rel="noopener noreferrer" href="'+s.url+'">'+esc(s.title)+' ↗<small>'+types[s.type]+'</small></a>';}).join('')+'<p class="rail-date">更新 '+l.updated+'<br>'+ (l.internal?'未验证生产部署或租户状态':l.id==='electron-chromium-processes'?'官方文档核验 2026-09-29；示例未实测':l.stage==='workbuddy'?'5.6.2 安装代码静态分析；未运行业务任务':'实验结果未独立复现')+'</p></aside></div>';
 const prose=document.querySelector('.prose');
 renderDiagrams(prose).catch(()=>{});
 prose.querySelectorAll('[data-atlas-math]').forEach(el=>{const equation=equations[Number(el.dataset.atlasMath)];if(equation)katex.render(equation.tex,el,{displayMode:equation.display,throwOnError:false,trust:false});});
 prose.querySelectorAll('a').forEach(a=>{if(/^https?:/.test(a.getAttribute('href')||'')){a.target='_blank';a.rel='noopener noreferrer';}});
 prose.querySelectorAll('table').forEach(t=>{const w=document.createElement('div');w.className='table-scroll';t.before(w);w.append(t);});
 document.querySelector('#toc').innerHTML=[...prose.querySelectorAll('h2')].map((h,i)=>{h.id='section-'+i;return '<button data-section="'+i+'">'+h.textContent+'</button>';}).join('');
 document.querySelectorAll('[data-section]').forEach(b=>b.onclick=()=>document.querySelector('#section-'+b.dataset.section).scrollIntoView({behavior:'smooth'}));
 document.querySelector('#status').value=e.status;document.querySelector('#status').onchange=ev=>{update(id,{status:ev.target.value});toast(storageOk?'阅读状态已保存':'保存失败，请导出笔记');};
 document.querySelector('#note').oninput=ev=>{update(id,{note:ev.target.value});document.querySelector('#save-status').textContent=storageOk?'已保存到此浏览器':'存储不可用，请立即导出备份';};
}
function sourcePage(){
 document.querySelector('#main').innerHTML='<div class="page-head"><span class="eyebrow">THE READING SHELF</span><h1>证据，也有人的视角</h1><p>技术事实回到原论文与代码，理解路径借助博客和实践讨论。</p></div><div class="filters"><label class="search-box"><span>⌕</span><input id="source-search" type="search" aria-label="搜索来源" placeholder="搜索作者、主题或来源…"></label><div class="pills">'+[['all','全部'],...Object.entries(types)].map(([id,name])=>'<button class="pill '+(filter===id?'selected':'')+'" data-source-type="'+id+'">'+name+'</button>').join('')+'</div></div><div id="source-results"></div>';
 let query='';function show(){const ss=sources.filter(s=>(filter==='all'||s.type===filter)&&[s.title,s.author,s.value].join('').toLowerCase().includes(query.toLowerCase()));document.querySelector('#source-results').innerHTML=ss.length?'<div class="source-grid">'+ss.map(s=>'<section class="source-card"><div class="source-meta"><span class="tag '+(s.type==='community'?'warm':'')+'">'+types[s.type]+'</span><small>'+esc(s.date)+'</small></div><h3><a href="'+s.url+'" target="_blank" rel="noopener noreferrer">'+esc(s.title)+' ↗</a></h3><p class="author">'+esc(s.author)+'</p><p>'+esc(s.value)+'</p><div class="source-coverage"><b>阅读范围</b><span>'+esc(s.coverage)+'</span><b>使用边界</b><span>'+esc(s.limit)+'</span></div></section>').join('')+'</div>':'<div class="empty">没有匹配来源。</div>';}
 show();document.querySelector('#source-search').oninput=e=>{query=e.target.value;show();};document.querySelectorAll('[data-source-type]').forEach(b=>b.onclick=()=>{filter=b.dataset.sourceType;document.querySelectorAll('[data-source-type]').forEach(x=>x.classList.toggle('selected',x===b));show();});
}
function exportNotes(){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='agent-atlas-notes-'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function notes(){
 const list=allLessons.filter(l=>entry(l.id).note||entry(l.id).status!=='unread');document.querySelector('#main').innerHTML='<div class="page-head"><span class="eyebrow">YOUR OWN WORDS</span><h1>留下问题，也留下理解</h1><p>笔记仅保存在当前网站的浏览器存储中。localhost 与线上站点不共享笔记，可导出后导入；只导入本站已有课程的记录，请保留原始备份。较新的同篇记录优先合并。</p></div><div class="notes-tools"><button class="button primary" id="export">导出笔记 ↓</button><label class="button light" for="import">导入笔记 ↑</label><input type="file" id="import" accept="application/json,.json" hidden></div><div class="note-list">'+(list.length?list.map(l=>'<section class="saved-note"><span class="tag">'+statusText[entry(l.id).status]+'</span><h2><a href="#/lesson/'+l.id+'">'+esc(l.title)+' ↗</a></h2><p>'+esc(entry(l.id).note||'还没有文字笔记。').replace(/\n/g,'<br>')+'</p><small>'+new Date(entry(l.id).updated).toLocaleString('zh-CN')+'</small></section>').join(''):'<div class="empty"><span>✎</span><h2>第一条笔记，从一个问题开始</h2><p>每篇课的底部都可以记录理解与疑问。</p><a class="text-link" href="#/lesson/llm-basics">打开第一篇课 →</a></div>')+'</div>';
 document.querySelector('#export').onclick=()=>{
   let panel=document.querySelector('#export-panel');
   if(!panel){panel=document.createElement('section');panel.id='export-panel';panel.className='export-panel';document.querySelector('.notes-tools').after(panel);}
   panel.innerHTML='<h2>笔记备份已生成</h2><p>可复制保存为 JSON 文件；普通浏览器也可下载。没有向远端发送数据。</p><textarea aria-label="导出的笔记 JSON" readonly></textarea><div><button class="button primary" id="copy-export">复制 JSON</button> <button class="button light" id="download-export">下载 JSON 文件</button></div>';
   panel.querySelector('textarea').value=JSON.stringify(state,null,2);
   document.querySelector('#copy-export').onclick=async()=>{try{await navigator.clipboard.writeText(panel.querySelector('textarea').value);toast('JSON 已复制，可粘贴保存为文件');}catch{panel.querySelector('textarea').focus();panel.querySelector('textarea').select();toast('已选中文本，请复制并保存为 JSON 文件');}};
   document.querySelector('#download-export').onclick=exportNotes;
 };document.querySelector('#import').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>3_000_000)throw new Error('文件过大，请使用本网站导出的笔记。');const incoming=validateState(JSON.parse(await file.text()),ids);state=mergeState(state,incoming);save();notes();toast(storageOk?'笔记已合并，较新记录已保留':'已合并到内存，请导出备份');}catch(err){toast(err.message||'导入失败，已有笔记未改动');e.target.value='';}};
}
function lab(){
 document.querySelector('#main').innerHTML='<div class="page-head"><span class="eyebrow">SMALL EXPERIMENTS, CLEARER INTUITION</span><h1>动一下参数，看看会怎样</h1><p>三个确定性教学实验。无需 GPU，不调用模型，不执行真实训练。</p></div><section class="lab-panel"><div class="lab-heading"><span class="lab-number">01</span><div><h2>上下文变长，KV 会多大？</h2><p>固定 batch = 1、32 层、head dim = 128；仅估算同构 MHA / GQA 的 KV。</p></div></div><div class="lab-split"><div class="controls"><label for="tokens">缓存长度 <output id="tokens-label"></output></label><input id="tokens" type="range" min="1024" max="131072" step="1024" value="32768"><label for="heads">KV heads</label><select id="heads"><option value="32">32 · MHA 示例</option><option value="8" selected>8 · GQA 示例</option><option value="1">1 · MQA 示例</option></select><label for="precision">每元素存储</label><select id="precision"><option value="2">2 bytes · FP16/BF16</option><option value="1">1 byte · 8-bit 理想估算</option></select></div><div class="lab-result"><small>仅 KV-cache</small><strong id="kv-result"></strong><div class="bar-track"><div id="kv-bar"></div></div><p>不含权重、临时张量和量化元数据；不能直接套到 MLA 或混合层。</p></div></div><a href="#/lesson/'+(allLessons.some(l=>l.id==='efficiency')?'efficiency':'context-window')+'" class="text-link">为什么这样计算？ →</a></section><section class="lab-panel"><div class="lab-heading"><span class="lab-number">02</span><div><h2>四次尝试，谁比基线更好？</h2><p>组内标准化 advantage：使用总体标准差，加 1e-8 防除零。</p></div></div><div class="reward-inputs">'+[1,0,0,1].map((x,i)=>'<label>尝试 '+(i+1)+'<input class="reward" aria-label="尝试 '+(i+1)+' 奖励" type="number" step="0.1" min="-100" max="100" value="'+x+'"></label>').join('')+'</div><div id="adv-result"></div><p class="lab-caveat">这里只演示奖励基线，不包含策略概率、KL、clipping 或反向传播。</p><a class="text-link" href="#/lesson/rl-foundations">回到 PPO / GRPO →</a></section><section class="lab-panel"><div class="lab-heading"><span class="lab-number">03</span><div><h2>双随机混合，保留了什么？</h2><p>输入两条流 [2, 6]，混合矩阵 [[a, 1-a], [1-a, a]]。</p></div></div><label for="mix">混合系数 a <output id="mix-label"></output></label><input id="mix" type="range" min="0" max="1" step="0.05" value="0.8"><div id="mix-result" class="mix-result"></div><p class="lab-caveat">总和不变，差异可以变化。这只说明残差混合的一个性质，不是整个 mHC 网络稳定性的证明。</p><a href="#/lesson/mhc" class="text-link">继续理解 mHC →</a></section>';
 function kv(){const tokens=+document.querySelector('#tokens').value, heads=+document.querySelector('#heads').value,bytes=+document.querySelector('#precision').value;const n=kvBytes({batch:1,layers:32,tokens,heads,dim:128,bytes})/1024**3;document.querySelector('#tokens-label').textContent=tokens.toLocaleString()+' tokens';document.querySelector('#kv-result').textContent=n.toFixed(2)+' GiB';document.querySelector('#kv-bar').style.width=Math.max(1,n/64*100)+'%';}kv();['tokens','heads','precision'].forEach(id=>document.querySelector('#'+id).oninput=kv);
 function adv(){const inputs=[...document.querySelectorAll('.reward')];if(inputs.some(x=>x.value===''||!x.validity.valid)){document.querySelector('#adv-result').innerHTML='<p role="status">请为每次尝试填写 -100 到 100 的数字。</p>';return;}const a=advantages(inputs.map(x=>+x.value));document.querySelector('#adv-result').innerHTML='<div class="adv-summary">均值 <b>'+a.mean.toFixed(2)+'</b>　标准差 <b>'+a.std.toFixed(2)+'</b></div><div class="adv-grid">'+a.values.map((x,i)=>'<div class="adv-cell '+(x>0?'positive':x<0?'negative':'neutral')+'"><small>尝试 '+(i+1)+'</small><strong>'+(x>0?'+':'')+x.toFixed(2)+'</strong></div>').join('')+'</div><p class="signal">'+(a.std<1e-10?'这组没有相对差异。全成功和全失败，都可能出现这个现象。':'正值相对较好，负值相对较差；不代表每一步的真实因果贡献。')+'</p>'; }adv();document.querySelectorAll('.reward').forEach(e=>e.oninput=adv);
 function mix(){const a=+document.querySelector('#mix').value;document.querySelector('#mix-label').textContent=a.toFixed(2);document.querySelector('#mix-result').innerHTML='<span>[2, 6]</span><b>→</b><span>['+(2*a+6*(1-a)).toFixed(2)+', '+(2*(1-a)+6*a).toFixed(2)+']</span><small>总和 = 8</small>'; }mix();document.querySelector('#mix').oninput=mix;
}
function render(){privateViewCleanup?.dispose();privateViewCleanup=undefined;document.body.classList.remove('nav-open');const [page,id]=(location.hash.replace(/^#\/?/,'')||'home').split('/');shell(['home','path','lab','sources','notes','interview','private'].includes(page)?page:'path');if(page==='home')home();else if(page==='path')path(id||'all');else if(page==='lesson')lesson(id);else if(page==='archive')archived();else if(page==='interview')interview();else if(page==='sources')sourcePage();else if(page==='notes')notes();else if(page==='lab')lab();else if(page==='private')privateViewCleanup=mountPrivateLibrary(document.querySelector('#main'),{payloadUrl:new URL('./private-library.json',document.baseURI).href,renderDiagrams});else document.querySelector('#main').innerHTML='<div class="empty"><h1>页面不存在</h1><a href="#/">返回首页</a></div>';document.title=(page==='lesson'?(allLessons.find(l=>l.id===id)?.title||'课程'):'知行图谱')+' · Agent Learning Atlas';window.scrollTo(0,0);}
window.addEventListener('hashchange',render);window.addEventListener('keydown',e=>{if(e.key==='/'&&!['INPUT','TEXTAREA','SELECT'].includes(document.activeElement.tagName)){e.preventDefault();location.hash='#/path';setTimeout(()=>document.querySelector('#course-search')?.focus(),30);}});render();
